//
//  SessionRecordingsStore.swift
//  EnglishHelper — Data (live adapter)
//
//  On-disk store + playback for live-session recordings (Application Support/SessionRecordings).
//  History rows persist only the FILE NAME — the container path changes across reinstalls, so
//  absolute URLs must never be stored. The live translator writes files here; this player reads
//  and deletes them.
//

import Foundation
import AVFoundation
import Domain

/// Directory resolution shared by the recorder (SonioxLiveTranslator) and the player below.
enum RecordingsDirectory {
    static func url() throws -> URL {
        let base = try FileManager.default.url(for: .applicationSupportDirectory,
                                               in: .userDomainMask, appropriateFor: nil, create: true)
        let dir = base.appending(path: "SessionRecordings", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    static func fileURL(named name: String) -> URL? {
        // Names are UUID-based and generated by us, but never trust a stored string enough to let
        // it escape the directory.
        guard !name.contains("/"), !name.contains("..") else { return nil }
        return try? url().appending(path: name)
    }
}

public final class SessionRecordingsPlayer: SessionRecordingsManaging, @unchecked Sendable {

    public init() {}

    public func exists(fileName: String) -> Bool {
        guard let url = RecordingsDirectory.fileURL(named: fileName) else { return false }
        return FileManager.default.fileExists(atPath: url.path)
    }

    public func delete(fileName: String) async {
        guard let url = RecordingsDirectory.fileURL(named: fileName) else { return }
        try? FileManager.default.removeItem(at: url)
    }

    public func sweep(keeping: Set<String>) async {
        guard let dir = try? RecordingsDirectory.url(),
              let files = try? FileManager.default.contentsOfDirectory(atPath: dir.path) else { return }
        for file in files where !keeping.contains(file) {
            try? FileManager.default.removeItem(at: dir.appending(path: file))
        }
    }

    public func play(fileName: String) -> AsyncThrowingStream<RecordingPlayback, Error> {
        AsyncThrowingStream { continuation in
            // A live session holds the shared audio session in .record — switching it to .playback
            // here would kill the running capture. Refuse instead of stealing the microphone.
            guard AVAudioSession.sharedInstance().category != .record else {
                continuation.finish(throwing: RecordingPlaybackError.busy)
                return
            }
            guard let url = RecordingsDirectory.fileURL(named: fileName),
                  FileManager.default.fileExists(atPath: url.path) else {
                continuation.finish(throwing: RecordingPlaybackError.missing)
                return
            }
            let box = PlaybackBox()
            // Cancelling the consuming task IS the stop API (house rule): stop playback and release
            // the shared audio session on every end — finish, cancel, or error.
            continuation.onTermination = { @Sendable _ in box.stop() }
            Task { @MainActor in
                do {
                    let session = AVAudioSession.sharedInstance()
                    try session.setCategory(.playback, mode: .spokenAudio, options: [.duckOthers])
                    try session.setActive(true)
                    let player = try AVAudioPlayer(contentsOf: url)
                    box.install(player)
                    guard !box.stopped else { return }   // cancelled while preparing
                    player.play()
                    // Poll for progress instead of a delegate: simpler, and the 5 Hz cadence is
                    // plenty for a progress bar.
                    while !box.stopped, player.isPlaying {
                        let progress = player.duration > 0 ? player.currentTime / player.duration : 0
                        continuation.yield(.playing(progress: min(1, max(0, progress))))
                        try await Task.sleep(for: .milliseconds(200))
                    }
                    if !box.stopped { continuation.yield(.finished) }
                    box.stop()
                    continuation.finish()
                } catch {
                    box.stop()
                    continuation.finish(throwing: RecordingPlaybackError.underlying(error.localizedDescription))
                }
            }
        }
    }

    /// Holds the player across the termination boundary; `stop()` is the single teardown chokepoint.
    private final class PlaybackBox: @unchecked Sendable {
        private let lock = NSLock()
        private var player: AVAudioPlayer?
        private var isStopped = false

        var stopped: Bool { lock.lock(); defer { lock.unlock() }; return isStopped }

        func install(_ player: AVAudioPlayer) {
            lock.lock(); defer { lock.unlock() }
            self.player = player
        }

        func stop() {
            lock.lock()
            let alreadyStopped = isStopped
            isStopped = true
            let player = self.player
            self.player = nil
            lock.unlock()
            guard !alreadyStopped else { return }
            player?.stop()
            try? AVAudioSession.sharedInstance().setActive(false, options: .notifyOthersOnDeactivation)
        }
    }
}
