//
//  LocCatalog.swift
//  EnglishHelper — DesignSystem
//
//  GENERATED — do not edit by hand. French/Spanish/German/Italian translations keyed by the EXACT
//  English string passed to Loc.t / DSLoc.t. Russian and English come from the call sites
//  themselves; this table only supplies the four added interface languages. Missing key -> falls
//  back to English. Regenerate with /tmp/gen_loc2.py after adding/changing UI strings.
//

import Foundation

public enum LocCatalog {
    public static let fr: [String: String] = [
        "Studied language": "Langue étudiée",
        "The language you're learning. Phrases are shown in it and all speech uses it.": "La langue que vous apprenez. Les phrases s'affichent dans cette langue et toute la synthèse vocale l'utilise.",
        "French": "Français",
        "Spanish": "Espagnol",
        "Copy explanation": "Copier l'explication",
        "Copy expression": "Copier l'expression",
        "Clear": "Effacer",
        "Copied": "Copié",
        "Explanation": "Explication",
        "Text in the language you're learning": "Texte dans la langue étudiée",
        "Tap to speak the language you're learning": "Touchez pour parler dans la langue étudiée",
        "Tap and speak the language you're learning": "Touchez et parlez dans la langue étudiée",
        "To hear your speech and translate it, the app needs the microphone. Nothing is recorded.": "Pour entendre votre voix et la traduire, l'app a besoin du microphone. Rien n'est enregistré.",
        "What do you want to say?": "Que voulez-vous dire ?",
        "Tap to speak your native language": "Touchez pour parler dans votre langue maternelle",
        "Tap and speak your native language": "Touchez et parlez dans votre langue maternelle",
        "Hold and speak your native language": "Maintenez et parlez dans votre langue maternelle",
        "Hold and speak the language you're learning": "Maintenez et parlez dans la langue étudiée",
        "Listening… release to get phrasings": "À l'écoute… relâchez pour obtenir des formulations",
        "Listening… release to translate or explain": "À l'écoute… relâchez pour traduire ou expliquer",
        "Tap to stop and get phrasings": "Touchez pour arrêter et obtenir des formulations",
        "Tap to stop and translate": "Touchez pour arrêter et traduire",
        "Tap to stop and get an explanation": "Touchez pour arrêter et obtenir une explication",
        "Tap to start dictating in your native language; a tone marks the start": "Touchez pour commencer à dicter dans votre langue maternelle ; un signal marque le début",
        "Tap to start dictating in the language you're learning; a tone marks the start": "Touchez pour commencer à dicter dans la langue étudiée ; un signal marque le début",
        "How do you say it?": "Comment dire ?",
        "Ask by voice or type a phrase — I'll offer three options at different politeness levels.": "Demandez à voix haute ou saisissez une phrase — je proposerai trois options à différents niveaux de politesse.",
        "Type a phrase — I'll offer three options at different politeness levels.": "Saisissez une phrase — je proposerai trois options à différents niveaux de politesse.",
        "To hear you and find phrasings, the app needs the microphone. Nothing is recorded.": "Pour vous entendre et proposer des formulations, l'app a besoin du microphone. Rien n'est enregistré.",
        "About": "À propos",
        "Add": "Ajouter",
        "Add expression": "Ajouter une expression",
        "Adding translation and examples…": "Ajout de la traduction et des exemples…",
        "Allow": "Autoriser",
        "Analogy": "Analogie",
        "Another photo": "Autre photo",
        "Appearance": "Apparence",
        "Ask by voice or type a phrase in Russian — I'll offer three options at different politeness levels.": "Demandez à voix haute ou saisissez une phrase en russe — je proposerai trois options à différents niveaux de politesse.",
        "Camera access": "Accès à la caméra",
        "Cancel": "Annuler",
        "Cancelled.": "Annulé.",
        "Casual": "Familier",
        "Casual, slangy": "Informel, argotique",
        "Check again": "Vérifier à nouveau",
        "Checking…": "Vérification…",
        "Choose a photo from the library": "Choisir une photo dans la galerie",
        "Claude connection": "Connexion à Claude",
        "Connected": "Connecté",
        "Connection error": "Erreur de connexion",
        "Context (optional)": "Contexte (facultatif)",
        "Copy": "Copier",
        "Copy English": "Copier l'anglais",
        "Copy translation": "Copier la traduction",
        "Couldn't connect": "Connexion impossible",
        "Couldn't create the export file.": "Impossible de créer le fichier d'export.",
        "Couldn't load": "Chargement impossible",
        "Couldn't load history.": "Impossible de charger l'historique.",
        "Couldn't load the list.": "Impossible de charger la liste.",
        "Couldn't parse the response. Try again.": "Impossible d'analyser la réponse. Réessayez.",
        "Couldn't process the image.": "Impossible de traiter l'image.",
        "Couldn't recognize speech. Type the text instead.": "Impossible de reconnaître la parole. Saisissez le texte à la place.",
        "Couldn't save to your study list.": "Impossible d'enregistrer dans votre liste d'étude.",
        "Dark": "Sombre",
        "Delete": "Supprimer",
        "Didn't catch that. Try again.": "Je n'ai pas compris. Réessayez.",
        "Done": "Terminé",
        "Double-tap to play": "Touchez deux fois pour écouter",
        "English": "Anglais",
        "English expression": "Expression anglaise",
        "Everyday conversational": "Conversation de tous les jours",
        "Explain": "Expliquer",
        "Explaining…": "Explication…",
        "Export": "Exporter",
        "Export list": "Exporter la liste",
        "Find phrasings": "Trouver des formulations",
        "Finding phrasings…": "Recherche de formulations…",
        "Formal and polite": "Formel et poli",
        "From library": "Depuis la galerie",
        "Get": "Comprendre",
        "Get it": "Comprendre",
        "History": "Historique",
        "How do you say it in English?": "Comment le dire en anglais ?",
        "How to say": "Comment dire",
        "In context": "En contexte",
        "Interface language": "Langue de l'interface",
        "Welcome": "Bienvenue",
        "Choose your languages to get started": "Choisissez vos langues pour commencer",
        "Get started": "Commencer",
        "The language the app is shown in.": "La langue dans laquelle l'application est affichée.",
        "Learned": "Appris",
        "Light": "Clair",
        "Listening": "À l'écoute",
        "Listening… tap to stop": "À l'écoute… touchez pour arrêter",
        "Loading…": "Chargement…",
        "Meaning": "Sens",
        "Microphone": "Microphone",
        "Microphone access": "Accès au microphone",
        "Mode": "Mode",
        "Model": "Modèle",
        "Native language": "Langue maternelle",
        "New expression": "Nouvelle expression",
        "New phrase": "Nouvelle phrase",
        "No Claude API key": "Pas de clé API Claude",
        "No Claude API key — options won't load. Add a key in Secrets.xcconfig.": "Pas de clé API Claude — les options ne se chargeront pas. Ajoutez une clé dans Secrets.xcconfig.",
        "No Claude API key — translation won't load. Add a key in Secrets.xcconfig.": "Pas de clé API Claude — la traduction ne se chargera pas. Ajoutez une clé dans Secrets.xcconfig.",
        "No Claude API key. Add one to continue.": "Pas de clé API Claude. Ajoutez-en une pour continuer.",
        "No Claude API key. Add one to get options.": "Pas de clé API Claude. Ajoutez-en une pour obtenir des options.",
        "No Claude API key. Add one to translate.": "Pas de clé API Claude. Ajoutez-en une pour traduire.",
        "No English text found in the photo. Try another image.": "Aucun texte anglais trouvé sur la photo. Essayez une autre image.",
        "No access to the microphone or speech recognition. Enable it in Settings, or type the text instead.": "Pas d'accès au microphone ou à la reconnaissance vocale. Activez-le dans Réglages, ou saisissez le texte.",
        "No connection": "Pas de connexion",
        "No connection. Check the internet and try again.": "Pas de connexion. Vérifiez Internet et réessayez.",
        "No history yet": "Pas encore d'historique",
        "Not learned": "Non appris",
        "Not now": "Plus tard",
        "Nothing yet": "Rien pour l'instant",
        "One moment…": "Un instant…",
        "Open result": "Ouvrir le résultat",
        "Photo translation": "Traduction photo",
        "Phrase tone": "Ton des phrases",
        "Play": "Écouter",
        "Play English": "Écouter l'anglais",
        "Play original": "Écouter l'original",
        "Play the English original": "Écouter l'original anglais",
        "Playing…": "Lecture…",
        "Polite": "Poli",
        "Reading and translating…": "Lecture et traduction…",
        "Ready": "Prêt",
        "Remove from study list": "Retirer de la liste d'étude",
        "Request": "Requête",
        "Request cancelled.": "Requête annulée.",
        "Retry": "Réessayer",
        "Russian": "Russe",
        "Save": "Enregistrer",
        "Save phrases from “Say it”, “Get it”, or “See it” — or add them manually.": "Enregistrez des phrases depuis « Dire », « Comprendre » ou « Voir » — ou ajoutez-les manuellement.",
        "Save to study list": "Enregistrer dans la liste d'étude",
        "Say": "Dire",
        "Say it": "Dire",
        "See": "Voir",
        "See it": "Voir",
        "Service is overloaded — try later": "Service surchargé — réessayez plus tard",
        "Service is overloaded — try later.": "Service surchargé — réessayez plus tard.",
        "Service unavailable": "Service indisponible",
        "Service unavailable. Try later.": "Service indisponible. Réessayez plus tard.",
        "Settings": "Réglages",
        "Slang": "Argot",
        "Snap a sign, menu, or page — I'll read the English and translate it.": "Photographiez un panneau, un menu ou une page — je lirai l'anglais et le traduirai.",
        "Something went wrong": "Une erreur s'est produite",
        "Something went wrong. Try again.": "Une erreur s'est produite. Réessayez.",
        "Speech recognition is unavailable. Type the text instead.": "La reconnaissance vocale est indisponible. Saisissez le texte à la place.",
        "Speech voice": "Voix de synthèse",
        "Study": "Étudier",
        "Study list": "Liste d'étude",
        "System": "Système",
        "Take a photo": "Prendre une photo",
        "Tap and speak English": "Touchez et parlez en anglais",
        "Tap and speak Russian": "Touchez et parlez en russe",
        "Tap to speak English": "Touchez pour parler en anglais",
        "Tap to speak Russian": "Touchez pour parler en russe",
        "Tap to stop": "Touchez pour arrêter",
        "Text in any language": "Texte dans n'importe quelle langue",
        "Text recognition error.": "Erreur de reconnaissance de texte.",
        "The language of translations and explanations on the Get it screen.": "La langue des traductions et des explications sur l'écran Comprendre.",
        "The list is empty — nothing to export.": "La liste est vide — rien à exporter.",
        "The service didn't respond in time": "Le service n'a pas répondu à temps",
        "The service didn't respond in time. Try again.": "Le service n'a pas répondu à temps. Réessayez.",
        "Theme": "Thème",
        "To hear your English speech and translate it, the app needs the microphone. Nothing is recorded.": "Pour entendre votre anglais et le traduire, l'app a besoin du microphone. Rien n'est enregistré.",
        "To hear your question in Russian and find English phrases, the app needs the microphone. Nothing is recorded.": "Pour entendre votre question en russe et trouver des phrases en anglais, l'app a besoin du microphone. Rien n'est enregistré.",
        "To read English text on a sign or menu, the app needs the camera. Nothing is sent anywhere without your action.": "Pour lire le texte anglais d'un panneau ou d'un menu, l'app a besoin de la caméra. Rien n'est envoyé sans votre action.",
        "Tone & register": "Ton et registre",
        "Translate": "Traduire",
        "Translate text from a photo": "Traduire le texte d'une photo",
        "Translating…": "Traduction…",
        "Translation": "Traduction",
        "Type a phrase in Russian — I'll offer three options at different politeness levels.": "Saisissez une phrase en russe — je proposerai trois options à différents niveaux de politesse.",
        "Type or dictate an expression. In Translate I'll render its meaning; in Explain I'll tell you what it means, how formal or blunt it sounds, and what it compares to.": "Saisissez ou dictez une expression. En mode Traduire, j'en donne le sens ; en mode Expliquer, je vous dis ce qu'elle signifie, à quel point elle est formelle ou directe, et à quoi elle ressemble.",
        "Unexpected response from the service": "Réponse inattendue du service",
        "Version": "Version",
        "What do you want to say in Russian?": "Que voulez-vous dire en russe ?",
        "What does it mean?": "Qu'est-ce que ça veut dire ?",
        "Without a Claude API key, the card is saved without translation or examples.": "Sans clé API Claude, la carte est enregistrée sans traduction ni exemples.",
        "Your requests will appear here: how-to-say, translations, and photo translations.": "Vos demandes apparaîtront ici : comment dire, traductions et traductions photo.",
        "German": "Allemand",
        "Italian": "Italien",
    ]

    public static let es: [String: String] = [
        "Studied language": "Idioma estudiado",
        "The language you're learning. Phrases are shown in it and all speech uses it.": "El idioma que estás aprendiendo. Las frases se muestran en él y toda la voz lo usa.",
        "French": "Francés",
        "Spanish": "Español",
        "Copy explanation": "Copiar la explicación",
        "Copy expression": "Copiar la expresión",
        "Clear": "Borrar",
        "Copied": "Copiado",
        "Explanation": "Explicación",
        "Text in the language you're learning": "Texto en el idioma que estudias",
        "Tap to speak the language you're learning": "Toca para hablar en el idioma que estudias",
        "Tap and speak the language you're learning": "Toca y habla en el idioma que estudias",
        "To hear your speech and translate it, the app needs the microphone. Nothing is recorded.": "Para escuchar tu voz y traducirla, la app necesita el micrófono. No se graba nada.",
        "What do you want to say?": "¿Qué quieres decir?",
        "Tap to speak your native language": "Toca para hablar en tu idioma nativo",
        "Tap and speak your native language": "Toca y habla en tu idioma nativo",
        "Hold and speak your native language": "Mantén pulsado y habla en tu idioma nativo",
        "Hold and speak the language you're learning": "Mantén pulsado y habla en el idioma que estás aprendiendo",
        "Listening… release to get phrasings": "Escuchando… suelta para obtener frases",
        "Listening… release to translate or explain": "Escuchando… suelta para traducir o explicar",
        "Tap to stop and get phrasings": "Toca para detener y obtener frases",
        "Tap to stop and translate": "Toca para detener y traducir",
        "Tap to stop and get an explanation": "Toca para detener y obtener una explicación",
        "Tap to start dictating in your native language; a tone marks the start": "Toca para empezar a dictar en tu idioma nativo; una señal marca el inicio",
        "Tap to start dictating in the language you're learning; a tone marks the start": "Toca para empezar a dictar en el idioma que estás aprendiendo; una señal marca el inicio",
        "How do you say it?": "¿Cómo se dice?",
        "Ask by voice or type a phrase — I'll offer three options at different politeness levels.": "Pregunta por voz o escribe una frase: te ofreceré tres opciones con distintos niveles de cortesía.",
        "Type a phrase — I'll offer three options at different politeness levels.": "Escribe una frase: te ofreceré tres opciones con distintos niveles de cortesía.",
        "To hear you and find phrasings, the app needs the microphone. Nothing is recorded.": "Para escucharte y sugerir frases, la app necesita el micrófono. No se graba nada.",
        "About": "Acerca de",
        "Add": "Añadir",
        "Add expression": "Añadir expresión",
        "Adding translation and examples…": "Añadiendo traducción y ejemplos…",
        "Allow": "Permitir",
        "Analogy": "Analogía",
        "Another photo": "Otra foto",
        "Appearance": "Apariencia",
        "Ask by voice or type a phrase in Russian — I'll offer three options at different politeness levels.": "Pregunta por voz o escribe una frase en ruso: te ofreceré tres opciones con distintos niveles de cortesía.",
        "Camera access": "Acceso a la cámara",
        "Cancel": "Cancelar",
        "Cancelled.": "Cancelado.",
        "Casual": "Informal",
        "Casual, slangy": "Informal, con jerga",
        "Check again": "Comprobar de nuevo",
        "Checking…": "Comprobando…",
        "Choose a photo from the library": "Elegir una foto de la galería",
        "Claude connection": "Conexión con Claude",
        "Connected": "Conectado",
        "Connection error": "Error de conexión",
        "Context (optional)": "Contexto (opcional)",
        "Copy": "Copiar",
        "Copy English": "Copiar el inglés",
        "Copy translation": "Copiar la traducción",
        "Couldn't connect": "No se pudo conectar",
        "Couldn't create the export file.": "No se pudo crear el archivo de exportación.",
        "Couldn't load": "No se pudo cargar",
        "Couldn't load history.": "No se pudo cargar el historial.",
        "Couldn't load the list.": "No se pudo cargar la lista.",
        "Couldn't parse the response. Try again.": "No se pudo procesar la respuesta. Inténtalo de nuevo.",
        "Couldn't process the image.": "No se pudo procesar la imagen.",
        "Couldn't recognize speech. Type the text instead.": "No se pudo reconocer el habla. Escribe el texto.",
        "Couldn't save to your study list.": "No se pudo guardar en tu lista de estudio.",
        "Dark": "Oscuro",
        "Delete": "Eliminar",
        "Didn't catch that. Try again.": "No lo he captado. Inténtalo de nuevo.",
        "Done": "Hecho",
        "Double-tap to play": "Toca dos veces para reproducir",
        "English": "Inglés",
        "English expression": "Expresión en inglés",
        "Everyday conversational": "Conversación cotidiana",
        "Explain": "Explicar",
        "Explaining…": "Explicando…",
        "Export": "Exportar",
        "Export list": "Exportar la lista",
        "Find phrasings": "Buscar variantes",
        "Finding phrasings…": "Buscando variantes…",
        "Formal and polite": "Formal y cortés",
        "From library": "Desde la galería",
        "Get": "Entender",
        "Get it": "Entender",
        "History": "Historial",
        "How do you say it in English?": "¿Cómo se dice en inglés?",
        "How to say": "Cómo decir",
        "In context": "En contexto",
        "Interface language": "Idioma de la interfaz",
        "Welcome": "Bienvenido",
        "Choose your languages to get started": "Elige tus idiomas para empezar",
        "Get started": "Empezar",
        "The language the app is shown in.": "El idioma en que se muestra la aplicación.",
        "Learned": "Aprendido",
        "Light": "Claro",
        "Listening": "Escuchando",
        "Listening… tap to stop": "Escuchando… toca para parar",
        "Loading…": "Cargando…",
        "Meaning": "Significado",
        "Microphone": "Micrófono",
        "Microphone access": "Acceso al micrófono",
        "Mode": "Modo",
        "Model": "Modelo",
        "Native language": "Idioma nativo",
        "New expression": "Nueva expresión",
        "New phrase": "Nueva frase",
        "No Claude API key": "Sin clave de API de Claude",
        "No Claude API key — options won't load. Add a key in Secrets.xcconfig.": "Sin clave de API de Claude: las opciones no se cargarán. Añade una clave en Secrets.xcconfig.",
        "No Claude API key — translation won't load. Add a key in Secrets.xcconfig.": "Sin clave de API de Claude: la traducción no se cargará. Añade una clave en Secrets.xcconfig.",
        "No Claude API key. Add one to continue.": "Sin clave de API de Claude. Añade una para continuar.",
        "No Claude API key. Add one to get options.": "Sin clave de API de Claude. Añade una para obtener opciones.",
        "No Claude API key. Add one to translate.": "Sin clave de API de Claude. Añade una para traducir.",
        "No English text found in the photo. Try another image.": "No se encontró texto en inglés en la foto. Prueba con otra imagen.",
        "No access to the microphone or speech recognition. Enable it in Settings, or type the text instead.": "Sin acceso al micrófono o al reconocimiento de voz. Actívalo en Ajustes o escribe el texto.",
        "No connection": "Sin conexión",
        "No connection. Check the internet and try again.": "Sin conexión. Comprueba Internet e inténtalo de nuevo.",
        "No history yet": "Aún no hay historial",
        "Not learned": "No aprendido",
        "Not now": "Ahora no",
        "Nothing yet": "Nada todavía",
        "One moment…": "Un momento…",
        "Open result": "Abrir resultado",
        "Photo translation": "Traducción de foto",
        "Phrase tone": "Tono de las frases",
        "Play": "Reproducir",
        "Play English": "Reproducir el inglés",
        "Play original": "Reproducir el original",
        "Play the English original": "Reproducir el original en inglés",
        "Playing…": "Reproduciendo…",
        "Polite": "Cortés",
        "Reading and translating…": "Leyendo y traduciendo…",
        "Ready": "Listo",
        "Remove from study list": "Quitar de la lista de estudio",
        "Request": "Solicitud",
        "Request cancelled.": "Solicitud cancelada.",
        "Retry": "Reintentar",
        "Russian": "Ruso",
        "Save": "Guardar",
        "Save phrases from “Say it”, “Get it”, or “See it” — or add them manually.": "Guarda frases desde «Decir», «Entender» o «Ver», o añádelas manualmente.",
        "Save to study list": "Guardar en la lista de estudio",
        "Say": "Decir",
        "Say it": "Decir",
        "See": "Ver",
        "See it": "Ver",
        "Service is overloaded — try later": "El servicio está saturado: inténtalo más tarde",
        "Service is overloaded — try later.": "El servicio está saturado: inténtalo más tarde.",
        "Service unavailable": "Servicio no disponible",
        "Service unavailable. Try later.": "Servicio no disponible. Inténtalo más tarde.",
        "Settings": "Ajustes",
        "Slang": "Jerga",
        "Snap a sign, menu, or page — I'll read the English and translate it.": "Haz una foto a un cartel, menú o página: leeré el inglés y lo traduciré.",
        "Something went wrong": "Algo salió mal",
        "Something went wrong. Try again.": "Algo salió mal. Inténtalo de nuevo.",
        "Speech recognition is unavailable. Type the text instead.": "El reconocimiento de voz no está disponible. Escribe el texto.",
        "Speech voice": "Voz de lectura",
        "Study": "Estudiar",
        "Study list": "Lista de estudio",
        "System": "Sistema",
        "Take a photo": "Hacer una foto",
        "Tap and speak English": "Toca y habla en inglés",
        "Tap and speak Russian": "Toca y habla en ruso",
        "Tap to speak English": "Toca para hablar en inglés",
        "Tap to speak Russian": "Toca para hablar en ruso",
        "Tap to stop": "Toca para parar",
        "Text in any language": "Texto en cualquier idioma",
        "Text recognition error.": "Error de reconocimiento de texto.",
        "The language of translations and explanations on the Get it screen.": "El idioma de las traducciones y explicaciones en la pantalla Entender.",
        "The list is empty — nothing to export.": "La lista está vacía: nada que exportar.",
        "The service didn't respond in time": "El servicio no respondió a tiempo",
        "The service didn't respond in time. Try again.": "El servicio no respondió a tiempo. Inténtalo de nuevo.",
        "Theme": "Tema",
        "To hear your English speech and translate it, the app needs the microphone. Nothing is recorded.": "Para escuchar tu inglés y traducirlo, la app necesita el micrófono. No se graba nada.",
        "To hear your question in Russian and find English phrases, the app needs the microphone. Nothing is recorded.": "Para escuchar tu pregunta en ruso y encontrar frases en inglés, la app necesita el micrófono. No se graba nada.",
        "To read English text on a sign or menu, the app needs the camera. Nothing is sent anywhere without your action.": "Para leer texto en inglés de un cartel o menú, la app necesita la cámara. No se envía nada sin tu acción.",
        "Tone & register": "Tono y registro",
        "Translate": "Traducir",
        "Translate text from a photo": "Traducir texto de una foto",
        "Translating…": "Traduciendo…",
        "Translation": "Traducción",
        "Type a phrase in Russian — I'll offer three options at different politeness levels.": "Escribe una frase en ruso: te ofreceré tres opciones con distintos niveles de cortesía.",
        "Type or dictate an expression. In Translate I'll render its meaning; in Explain I'll tell you what it means, how formal or blunt it sounds, and what it compares to.": "Escribe o dicta una expresión. En Traducir te doy su significado; en Explicar te digo qué significa, cómo de formal o directa suena y con qué se puede comparar.",
        "Unexpected response from the service": "Respuesta inesperada del servicio",
        "Version": "Versión",
        "What do you want to say in Russian?": "¿Qué quieres decir en ruso?",
        "What does it mean?": "¿Qué significa?",
        "Without a Claude API key, the card is saved without translation or examples.": "Sin una clave de API de Claude, la tarjeta se guarda sin traducción ni ejemplos.",
        "Your requests will appear here: how-to-say, translations, and photo translations.": "Tus solicitudes aparecerán aquí: cómo decir, traducciones y traducciones de fotos.",
        "German": "Alemán",
        "Italian": "Italiano",
    ]

    public static let de: [String: String] = [
        "Studied language": "Lernsprache",
        "The language you're learning. Phrases are shown in it and all speech uses it.": "Die Sprache, die du lernst. Phrasen werden in ihr angezeigt und die gesamte Sprachausgabe verwendet sie.",
        "French": "Französisch",
        "Spanish": "Spanisch",
        "Copy explanation": "Erklärung kopieren",
        "Copy expression": "Ausdruck kopieren",
        "Clear": "Löschen",
        "Copied": "Kopiert",
        "Explanation": "Erklärung",
        "Text in the language you're learning": "Text in der Sprache, die du lernst",
        "Tap to speak the language you're learning": "Tippen, um in der Lernsprache zu sprechen",
        "Tap and speak the language you're learning": "Tippen und in der Lernsprache sprechen",
        "To hear your speech and translate it, the app needs the microphone. Nothing is recorded.": "Um deine Sprache zu hören und zu übersetzen, benötigt die App das Mikrofon. Es wird nichts aufgezeichnet.",
        "What do you want to say?": "Was möchtest du sagen?",
        "Tap to speak your native language": "Tippen, um in deiner Muttersprache zu sprechen",
        "Tap and speak your native language": "Tippen und in deiner Muttersprache sprechen",
        "Hold and speak your native language": "Halten und in deiner Muttersprache sprechen",
        "Hold and speak the language you're learning": "Halten und in der Lernsprache sprechen",
        "Listening… release to get phrasings": "Ich höre zu … loslassen, um Formulierungen zu erhalten",
        "Listening… release to translate or explain": "Ich höre zu … loslassen zum Übersetzen oder Erklären",
        "Tap to stop and get phrasings": "Tippen, um zu stoppen und Formulierungen zu erhalten",
        "Tap to stop and translate": "Tippen, um zu stoppen und zu übersetzen",
        "Tap to stop and get an explanation": "Tippen, um zu stoppen und eine Erklärung zu erhalten",
        "Tap to start dictating in your native language; a tone marks the start": "Tippen, um das Diktieren in deiner Muttersprache zu starten; ein Ton markiert den Beginn",
        "Tap to start dictating in the language you're learning; a tone marks the start": "Tippen, um das Diktieren in der Lernsprache zu starten; ein Ton markiert den Beginn",
        "How do you say it?": "Wie sagt man das?",
        "Ask by voice or type a phrase — I'll offer three options at different politeness levels.": "Frag per Sprache oder tippe eine Phrase – ich biete drei Optionen mit unterschiedlichen Höflichkeitsstufen.",
        "Type a phrase — I'll offer three options at different politeness levels.": "Tippe eine Phrase – ich biete drei Optionen mit unterschiedlichen Höflichkeitsstufen.",
        "To hear you and find phrasings, the app needs the microphone. Nothing is recorded.": "Um dich zu hören und Formulierungen zu finden, benötigt die App das Mikrofon. Es wird nichts aufgezeichnet.",
        "About": "Über die App",
        "Add": "Hinzufügen",
        "Add expression": "Ausdruck hinzufügen",
        "Adding translation and examples…": "Übersetzung und Beispiele werden hinzugefügt…",
        "Allow": "Erlauben",
        "Analogy": "Analogie",
        "Another photo": "Anderes Foto",
        "Appearance": "Darstellung",
        "Ask by voice or type a phrase in Russian — I'll offer three options at different politeness levels.": "Frag per Sprache oder tippe eine Phrase auf Russisch – ich biete drei Optionen mit unterschiedlichen Höflichkeitsstufen.",
        "Camera access": "Kamerazugriff",
        "Cancel": "Abbrechen",
        "Cancelled.": "Abgebrochen.",
        "Casual": "Locker",
        "Casual, slangy": "Locker, salopp",
        "Check again": "Erneut prüfen",
        "Checking…": "Prüfe…",
        "Choose a photo from the library": "Ein Foto aus der Galerie wählen",
        "Claude connection": "Claude-Verbindung",
        "Connected": "Verbunden",
        "Connection error": "Verbindungsfehler",
        "Context (optional)": "Kontext (optional)",
        "Copy": "Kopieren",
        "Copy English": "Englisch kopieren",
        "Copy translation": "Übersetzung kopieren",
        "Couldn't connect": "Verbindung fehlgeschlagen",
        "Couldn't create the export file.": "Exportdatei konnte nicht erstellt werden.",
        "Couldn't load": "Laden fehlgeschlagen",
        "Couldn't load history.": "Verlauf konnte nicht geladen werden.",
        "Couldn't load the list.": "Liste konnte nicht geladen werden.",
        "Couldn't parse the response. Try again.": "Antwort konnte nicht verarbeitet werden. Versuche es erneut.",
        "Couldn't process the image.": "Bild konnte nicht verarbeitet werden.",
        "Couldn't recognize speech. Type the text instead.": "Sprache konnte nicht erkannt werden. Gib den Text stattdessen ein.",
        "Couldn't save to your study list.": "Konnte nicht in deiner Lernliste gespeichert werden.",
        "Dark": "Dunkel",
        "Delete": "Löschen",
        "Didn't catch that. Try again.": "Nicht verstanden. Versuche es erneut.",
        "Done": "Fertig",
        "Double-tap to play": "Zum Abspielen doppeltippen",
        "English": "Englisch",
        "English expression": "Englischer Ausdruck",
        "Everyday conversational": "Alltagssprache",
        "Explain": "Erklären",
        "Explaining…": "Erkläre…",
        "Export": "Exportieren",
        "Export list": "Liste exportieren",
        "Find phrasings": "Formulierungen finden",
        "Finding phrasings…": "Suche Formulierungen…",
        "Formal and polite": "Förmlich und höflich",
        "From library": "Aus der Galerie",
        "Get": "Verstehen",
        "Get it": "Verstehen",
        "History": "Verlauf",
        "How do you say it in English?": "Wie sagt man das auf Englisch?",
        "How to say": "Wie sagt man",
        "In context": "Im Kontext",
        "Interface language": "Sprache der Benutzeroberfläche",
        "Welcome": "Willkommen",
        "Choose your languages to get started": "Wähle deine Sprachen, um zu beginnen",
        "Get started": "Loslegen",
        "The language the app is shown in.": "Die Sprache, in der die App angezeigt wird.",
        "Learned": "Gelernt",
        "Light": "Hell",
        "Listening": "Höre zu",
        "Listening… tap to stop": "Höre zu… zum Stoppen tippen",
        "Loading…": "Lädt…",
        "Meaning": "Bedeutung",
        "Microphone": "Mikrofon",
        "Microphone access": "Mikrofonzugriff",
        "Mode": "Modus",
        "Model": "Modell",
        "Native language": "Muttersprache",
        "New expression": "Neuer Ausdruck",
        "New phrase": "Neue Phrase",
        "No Claude API key": "Kein Claude-API-Schlüssel",
        "No Claude API key — options won't load. Add a key in Secrets.xcconfig.": "Kein Claude-API-Schlüssel – Optionen werden nicht geladen. Füge einen Schlüssel in Secrets.xcconfig hinzu.",
        "No Claude API key — translation won't load. Add a key in Secrets.xcconfig.": "Kein Claude-API-Schlüssel – Übersetzung wird nicht geladen. Füge einen Schlüssel in Secrets.xcconfig hinzu.",
        "No Claude API key. Add one to continue.": "Kein Claude-API-Schlüssel. Füge einen hinzu, um fortzufahren.",
        "No Claude API key. Add one to get options.": "Kein Claude-API-Schlüssel. Füge einen hinzu, um Optionen zu erhalten.",
        "No Claude API key. Add one to translate.": "Kein Claude-API-Schlüssel. Füge einen hinzu, um zu übersetzen.",
        "No English text found in the photo. Try another image.": "Kein englischer Text im Foto gefunden. Versuche ein anderes Bild.",
        "No access to the microphone or speech recognition. Enable it in Settings, or type the text instead.": "Kein Zugriff auf Mikrofon oder Spracherkennung. Aktiviere ihn in den Einstellungen oder gib den Text ein.",
        "No connection": "Keine Verbindung",
        "No connection. Check the internet and try again.": "Keine Verbindung. Prüfe das Internet und versuche es erneut.",
        "No history yet": "Noch kein Verlauf",
        "Not learned": "Nicht gelernt",
        "Not now": "Jetzt nicht",
        "Nothing yet": "Noch nichts",
        "One moment…": "Einen Moment…",
        "Open result": "Ergebnis öffnen",
        "Photo translation": "Foto-Übersetzung",
        "Phrase tone": "Tonfall der Phrasen",
        "Play": "Abspielen",
        "Play English": "Englisch abspielen",
        "Play original": "Original abspielen",
        "Play the English original": "Englisches Original abspielen",
        "Playing…": "Spielt ab…",
        "Polite": "Höflich",
        "Reading and translating…": "Lese und übersetze…",
        "Ready": "Bereit",
        "Remove from study list": "Aus der Lernliste entfernen",
        "Request": "Anfrage",
        "Request cancelled.": "Anfrage abgebrochen.",
        "Retry": "Erneut versuchen",
        "Russian": "Russisch",
        "Save": "Speichern",
        "Save phrases from “Say it”, “Get it”, or “See it” — or add them manually.": "Speichere Phrasen aus “Sagen”, “Verstehen” oder “Sehen” – oder füge sie manuell hinzu.",
        "Save to study list": "In Lernliste speichern",
        "Say": "Sagen",
        "Say it": "Sagen",
        "See": "Sehen",
        "See it": "Sehen",
        "Service is overloaded — try later": "Dienst überlastet – versuche es später",
        "Service is overloaded — try later.": "Dienst überlastet – versuche es später.",
        "Service unavailable": "Dienst nicht verfügbar",
        "Service unavailable. Try later.": "Dienst nicht verfügbar. Versuche es später.",
        "Settings": "Einstellungen",
        "Slang": "Slang",
        "Snap a sign, menu, or page — I'll read the English and translate it.": "Fotografiere ein Schild, eine Speisekarte oder eine Seite – ich lese das Englische und übersetze es.",
        "Something went wrong": "Etwas ist schiefgelaufen",
        "Something went wrong. Try again.": "Etwas ist schiefgelaufen. Versuche es erneut.",
        "Speech recognition is unavailable. Type the text instead.": "Spracherkennung ist nicht verfügbar. Gib den Text stattdessen ein.",
        "Speech voice": "Sprachausgabe-Stimme",
        "Study": "Lernen",
        "Study list": "Lernliste",
        "System": "System",
        "Take a photo": "Ein Foto aufnehmen",
        "Tap and speak English": "Tippen und Englisch sprechen",
        "Tap and speak Russian": "Tippen und Russisch sprechen",
        "Tap to speak English": "Tippen, um Englisch zu sprechen",
        "Tap to speak Russian": "Tippen, um Russisch zu sprechen",
        "Tap to stop": "Zum Stoppen tippen",
        "Text in any language": "Text in beliebiger Sprache",
        "Text recognition error.": "Texterkennungsfehler.",
        "The language of translations and explanations on the Get it screen.": "Die Sprache der Übersetzungen und Erklärungen im Verstehen-Bildschirm.",
        "The list is empty — nothing to export.": "Die Liste ist leer – nichts zu exportieren.",
        "The service didn't respond in time": "Der Dienst hat nicht rechtzeitig geantwortet",
        "The service didn't respond in time. Try again.": "Der Dienst hat nicht rechtzeitig geantwortet. Versuche es erneut.",
        "Theme": "Design",
        "To hear your English speech and translate it, the app needs the microphone. Nothing is recorded.": "Um dein Englisch zu hören und zu übersetzen, benötigt die App das Mikrofon. Es wird nichts aufgezeichnet.",
        "To hear your question in Russian and find English phrases, the app needs the microphone. Nothing is recorded.": "Um deine Frage auf Russisch zu hören und englische Phrasen zu finden, benötigt die App das Mikrofon. Es wird nichts aufgezeichnet.",
        "To read English text on a sign or menu, the app needs the camera. Nothing is sent anywhere without your action.": "Um englischen Text auf einem Schild oder einer Speisekarte zu lesen, benötigt die App die Kamera. Ohne deine Aktion wird nichts gesendet.",
        "Tone & register": "Ton & Register",
        "Translate": "Übersetzen",
        "Translate text from a photo": "Text aus einem Foto übersetzen",
        "Translating…": "Übersetze…",
        "Translation": "Übersetzung",
        "Type a phrase in Russian — I'll offer three options at different politeness levels.": "Tippe eine Phrase auf Russisch – ich biete drei Optionen mit unterschiedlichen Höflichkeitsstufen.",
        "Type or dictate an expression. In Translate I'll render its meaning; in Explain I'll tell you what it means, how formal or blunt it sounds, and what it compares to.": "Tippe oder diktiere einen Ausdruck. In “Übersetzen” gebe ich seine Bedeutung wieder; in “Erklären” sage ich dir, was er bedeutet, wie förmlich oder direkt er klingt und womit er vergleichbar ist.",
        "Unexpected response from the service": "Unerwartete Antwort vom Dienst",
        "Version": "Version",
        "What do you want to say in Russian?": "Was möchtest du auf Russisch sagen?",
        "What does it mean?": "Was bedeutet das?",
        "Without a Claude API key, the card is saved without translation or examples.": "Ohne Claude-API-Schlüssel wird die Karte ohne Übersetzung oder Beispiele gespeichert.",
        "Your requests will appear here: how-to-say, translations, and photo translations.": "Deine Anfragen erscheinen hier: Wie-sagt-man, Übersetzungen und Foto-Übersetzungen.",
        "German": "Deutsch",
        "Italian": "Italienisch",
    ]

    public static let it: [String: String] = [
        "Studied language": "Lingua studiata",
        "The language you're learning. Phrases are shown in it and all speech uses it.": "La lingua che stai imparando. Le frasi vengono mostrate in essa e tutta la sintesi vocale la usa.",
        "French": "Francese",
        "Spanish": "Spagnolo",
        "Copy explanation": "Copia la spiegazione",
        "Copy expression": "Copia l'espressione",
        "Clear": "Cancella",
        "Copied": "Copiato",
        "Explanation": "Spiegazione",
        "Text in the language you're learning": "Testo nella lingua che stai imparando",
        "Tap to speak the language you're learning": "Tocca per parlare nella lingua che stai imparando",
        "Tap and speak the language you're learning": "Tocca e parla nella lingua che stai imparando",
        "To hear your speech and translate it, the app needs the microphone. Nothing is recorded.": "Per ascoltare la tua voce e tradurla, l'app ha bisogno del microfono. Non viene registrato nulla.",
        "What do you want to say?": "Cosa vuoi dire?",
        "Tap to speak your native language": "Tocca per parlare nella tua lingua madre",
        "Tap and speak your native language": "Tocca e parla nella tua lingua madre",
        "Hold and speak your native language": "Tieni premuto e parla nella tua lingua madre",
        "Hold and speak the language you're learning": "Tieni premuto e parla nella lingua che stai imparando",
        "Listening… release to get phrasings": "In ascolto… rilascia per ottenere formulazioni",
        "Listening… release to translate or explain": "In ascolto… rilascia per tradurre o spiegare",
        "Tap to stop and get phrasings": "Tocca per fermare e ottenere formulazioni",
        "Tap to stop and translate": "Tocca per fermare e tradurre",
        "Tap to stop and get an explanation": "Tocca per fermare e ottenere una spiegazione",
        "Tap to start dictating in your native language; a tone marks the start": "Tocca per iniziare a dettare nella tua lingua madre; un segnale indica l'inizio",
        "Tap to start dictating in the language you're learning; a tone marks the start": "Tocca per iniziare a dettare nella lingua che stai imparando; un segnale indica l'inizio",
        "How do you say it?": "Come si dice?",
        "Ask by voice or type a phrase — I'll offer three options at different politeness levels.": "Chiedi a voce o scrivi una frase: ti offrirò tre opzioni con diversi livelli di cortesia.",
        "Type a phrase — I'll offer three options at different politeness levels.": "Scrivi una frase: ti offrirò tre opzioni con diversi livelli di cortesia.",
        "To hear you and find phrasings, the app needs the microphone. Nothing is recorded.": "Per ascoltarti e trovare formulazioni, l'app ha bisogno del microfono. Non viene registrato nulla.",
        "About": "Informazioni",
        "Add": "Aggiungi",
        "Add expression": "Aggiungi espressione",
        "Adding translation and examples…": "Aggiunta di traduzione ed esempi…",
        "Allow": "Consenti",
        "Analogy": "Analogia",
        "Another photo": "Altra foto",
        "Appearance": "Aspetto",
        "Ask by voice or type a phrase in Russian — I'll offer three options at different politeness levels.": "Chiedi a voce o scrivi una frase in russo: ti offrirò tre opzioni con diversi livelli di cortesia.",
        "Camera access": "Accesso alla fotocamera",
        "Cancel": "Annulla",
        "Cancelled.": "Annullato.",
        "Casual": "Informale",
        "Casual, slangy": "Informale, gergale",
        "Check again": "Controlla di nuovo",
        "Checking…": "Controllo…",
        "Choose a photo from the library": "Scegli una foto dalla galleria",
        "Claude connection": "Connessione a Claude",
        "Connected": "Connesso",
        "Connection error": "Errore di connessione",
        "Context (optional)": "Contesto (facoltativo)",
        "Copy": "Copia",
        "Copy English": "Copia l'inglese",
        "Copy translation": "Copia la traduzione",
        "Couldn't connect": "Impossibile connettersi",
        "Couldn't create the export file.": "Impossibile creare il file di esportazione.",
        "Couldn't load": "Impossibile caricare",
        "Couldn't load history.": "Impossibile caricare la cronologia.",
        "Couldn't load the list.": "Impossibile caricare l'elenco.",
        "Couldn't parse the response. Try again.": "Impossibile analizzare la risposta. Riprova.",
        "Couldn't process the image.": "Impossibile elaborare l'immagine.",
        "Couldn't recognize speech. Type the text instead.": "Impossibile riconoscere il parlato. Digita il testo.",
        "Couldn't save to your study list.": "Impossibile salvare nel tuo elenco di studio.",
        "Dark": "Scuro",
        "Delete": "Elimina",
        "Didn't catch that. Try again.": "Non ho capito. Riprova.",
        "Done": "Fine",
        "Double-tap to play": "Tocca due volte per riprodurre",
        "English": "Inglese",
        "English expression": "Espressione inglese",
        "Everyday conversational": "Conversazione quotidiana",
        "Explain": "Spiega",
        "Explaining…": "Spiegazione…",
        "Export": "Esporta",
        "Export list": "Esporta l'elenco",
        "Find phrasings": "Trova formulazioni",
        "Finding phrasings…": "Ricerca formulazioni…",
        "Formal and polite": "Formale e cortese",
        "From library": "Dalla galleria",
        "Get": "Capire",
        "Get it": "Capire",
        "History": "Cronologia",
        "How do you say it in English?": "Come si dice in inglese?",
        "How to say": "Come dire",
        "In context": "Nel contesto",
        "Interface language": "Lingua dell'interfaccia",
        "Welcome": "Benvenuto",
        "Choose your languages to get started": "Scegli le lingue per iniziare",
        "Get started": "Inizia",
        "The language the app is shown in.": "La lingua in cui viene mostrata l'app.",
        "Learned": "Imparato",
        "Light": "Chiaro",
        "Listening": "In ascolto",
        "Listening… tap to stop": "In ascolto… tocca per fermare",
        "Loading…": "Caricamento…",
        "Meaning": "Significato",
        "Microphone": "Microfono",
        "Microphone access": "Accesso al microfono",
        "Mode": "Modalità",
        "Model": "Modello",
        "Native language": "Lingua madre",
        "New expression": "Nuova espressione",
        "New phrase": "Nuova frase",
        "No Claude API key": "Nessuna chiave API Claude",
        "No Claude API key — options won't load. Add a key in Secrets.xcconfig.": "Nessuna chiave API Claude: le opzioni non verranno caricate. Aggiungi una chiave in Secrets.xcconfig.",
        "No Claude API key — translation won't load. Add a key in Secrets.xcconfig.": "Nessuna chiave API Claude: la traduzione non verrà caricata. Aggiungi una chiave in Secrets.xcconfig.",
        "No Claude API key. Add one to continue.": "Nessuna chiave API Claude. Aggiungine una per continuare.",
        "No Claude API key. Add one to get options.": "Nessuna chiave API Claude. Aggiungine una per ottenere le opzioni.",
        "No Claude API key. Add one to translate.": "Nessuna chiave API Claude. Aggiungine una per tradurre.",
        "No English text found in the photo. Try another image.": "Nessun testo inglese trovato nella foto. Prova un'altra immagine.",
        "No access to the microphone or speech recognition. Enable it in Settings, or type the text instead.": "Nessun accesso al microfono o al riconoscimento vocale. Attivalo in Impostazioni o digita il testo.",
        "No connection": "Nessuna connessione",
        "No connection. Check the internet and try again.": "Nessuna connessione. Controlla Internet e riprova.",
        "No history yet": "Ancora nessuna cronologia",
        "Not learned": "Non imparato",
        "Not now": "Non ora",
        "Nothing yet": "Ancora niente",
        "One moment…": "Un momento…",
        "Open result": "Apri il risultato",
        "Photo translation": "Traduzione foto",
        "Phrase tone": "Tono delle frasi",
        "Play": "Riproduci",
        "Play English": "Riproduci l'inglese",
        "Play original": "Riproduci l'originale",
        "Play the English original": "Riproduci l'originale inglese",
        "Playing…": "Riproduzione…",
        "Polite": "Cortese",
        "Reading and translating…": "Lettura e traduzione…",
        "Ready": "Pronto",
        "Remove from study list": "Rimuovi dall'elenco di studio",
        "Request": "Richiesta",
        "Request cancelled.": "Richiesta annullata.",
        "Retry": "Riprova",
        "Russian": "Russo",
        "Save": "Salva",
        "Save phrases from “Say it”, “Get it”, or “See it” — or add them manually.": "Salva frasi da «Dire», «Capire» o «Vedere» — o aggiungile manualmente.",
        "Save to study list": "Salva nell'elenco di studio",
        "Say": "Dire",
        "Say it": "Dire",
        "See": "Vedere",
        "See it": "Vedere",
        "Service is overloaded — try later": "Servizio sovraccarico — riprova più tardi",
        "Service is overloaded — try later.": "Servizio sovraccarico — riprova più tardi.",
        "Service unavailable": "Servizio non disponibile",
        "Service unavailable. Try later.": "Servizio non disponibile. Riprova più tardi.",
        "Settings": "Impostazioni",
        "Slang": "Gergo",
        "Snap a sign, menu, or page — I'll read the English and translate it.": "Fotografa un cartello, un menu o una pagina: leggerò l'inglese e lo tradurrò.",
        "Something went wrong": "Qualcosa è andato storto",
        "Something went wrong. Try again.": "Qualcosa è andato storto. Riprova.",
        "Speech recognition is unavailable. Type the text instead.": "Il riconoscimento vocale non è disponibile. Digita il testo.",
        "Speech voice": "Voce della sintesi",
        "Study": "Studio",
        "Study list": "Elenco di studio",
        "System": "Sistema",
        "Take a photo": "Scatta una foto",
        "Tap and speak English": "Tocca e parla in inglese",
        "Tap and speak Russian": "Tocca e parla in russo",
        "Tap to speak English": "Tocca per parlare in inglese",
        "Tap to speak Russian": "Tocca per parlare in russo",
        "Tap to stop": "Tocca per fermare",
        "Text in any language": "Testo in qualsiasi lingua",
        "Text recognition error.": "Errore di riconoscimento del testo.",
        "The language of translations and explanations on the Get it screen.": "La lingua delle traduzioni e delle spiegazioni nella schermata Capire.",
        "The list is empty — nothing to export.": "L'elenco è vuoto — niente da esportare.",
        "The service didn't respond in time": "Il servizio non ha risposto in tempo",
        "The service didn't respond in time. Try again.": "Il servizio non ha risposto in tempo. Riprova.",
        "Theme": "Tema",
        "To hear your English speech and translate it, the app needs the microphone. Nothing is recorded.": "Per ascoltare il tuo inglese e tradurlo, l'app ha bisogno del microfono. Non viene registrato nulla.",
        "To hear your question in Russian and find English phrases, the app needs the microphone. Nothing is recorded.": "Per ascoltare la tua domanda in russo e trovare frasi in inglese, l'app ha bisogno del microfono. Non viene registrato nulla.",
        "To read English text on a sign or menu, the app needs the camera. Nothing is sent anywhere without your action.": "Per leggere il testo inglese su un cartello o un menu, l'app ha bisogno della fotocamera. Niente viene inviato senza la tua azione.",
        "Tone & register": "Tono e registro",
        "Translate": "Traduci",
        "Translate text from a photo": "Traduci il testo da una foto",
        "Translating…": "Traduzione…",
        "Translation": "Traduzione",
        "Type a phrase in Russian — I'll offer three options at different politeness levels.": "Scrivi una frase in russo: ti offrirò tre opzioni con diversi livelli di cortesia.",
        "Type or dictate an expression. In Translate I'll render its meaning; in Explain I'll tell you what it means, how formal or blunt it sounds, and what it compares to.": "Scrivi o detta un'espressione. In Traduci ne rendo il significato; in Spiega ti dico cosa significa, quanto suona formale o diretta e a cosa si può paragonare.",
        "Unexpected response from the service": "Risposta inattesa dal servizio",
        "Version": "Versione",
        "What do you want to say in Russian?": "Cosa vuoi dire in russo?",
        "What does it mean?": "Cosa significa?",
        "Without a Claude API key, the card is saved without translation or examples.": "Senza una chiave API Claude, la scheda viene salvata senza traduzione né esempi.",
        "Your requests will appear here: how-to-say, translations, and photo translations.": "Le tue richieste appariranno qui: come dire, traduzioni e traduzioni di foto.",
        "German": "Tedesco",
        "Italian": "Italiano",
    ]
}
