//
//  LocCatalog.swift
//  EnglishHelper — DesignSystem
//
//  GENERATED — do not edit by hand. French/Spanish translations keyed by the EXACT English string
//  passed to Loc.t / DSLoc.t. Russian and English come from the call sites themselves; this table
//  only supplies the two added interface languages. Missing key -> falls back to English.
//  Regenerate with /tmp/gen_loc.py after adding/changing UI strings.
//

import Foundation

public enum LocCatalog {
    public static let fr: [String: String] = [
        "Studied language": "Langue étudiée",
        "The language you're learning. Phrases are shown in it and all speech uses it.": "La langue que vous apprenez. Les phrases s'affichent dans cette langue et toute la synthèse vocale l'utilise.",
        "French": "Français",
        "Spanish": "Espagnol",
        "Copy explanation": "Copier l'explication",
        "Copy expression": "Copier l'expression",
        "Clear": "Effacer",
        "Copied": "Copié",
        "Explanation": "Explication",
        "Text in the language you're learning": "Texte dans la langue étudiée",
        "Tap to speak the language you're learning": "Touchez pour parler dans la langue étudiée",
        "Tap and speak the language you're learning": "Touchez et parlez dans la langue étudiée",
        "To hear your speech and translate it, the app needs the microphone. Nothing is recorded.": "Pour entendre votre voix et la traduire, l'app a besoin du microphone. Rien n'est enregistré.",
        "What do you want to say?": "Que voulez-vous dire ?",
        "Tap to speak your native language": "Touchez pour parler dans votre langue maternelle",
        "Tap and speak your native language": "Touchez et parlez dans votre langue maternelle",
        "How do you say it?": "Comment dire ?",
        "Ask by voice or type a phrase — I'll offer three options at different politeness levels.": "Demandez à voix haute ou saisissez une phrase — je proposerai trois options à différents niveaux de politesse.",
        "Type a phrase — I'll offer three options at different politeness levels.": "Saisissez une phrase — je proposerai trois options à différents niveaux de politesse.",
        "To hear you and find phrasings, the app needs the microphone. Nothing is recorded.": "Pour vous entendre et proposer des formulations, l'app a besoin du microphone. Rien n'est enregistré.",
        "About": "À propos",
        "Add": "Ajouter",
        "Add expression": "Ajouter une expression",
        "Adding translation and examples…": "Ajout de la traduction et des exemples…",
        "Allow": "Autoriser",
        "Analogy": "Analogie",
        "Another photo": "Autre photo",
        "Appearance": "Apparence",
        "Ask by voice or type a phrase in Russian — I'll offer three options at different politeness levels.": "Demandez à voix haute ou saisissez une phrase en russe — je proposerai trois options à différents niveaux de politesse.",
        "Camera access": "Accès à la caméra",
        "Cancel": "Annuler",
        "Cancelled.": "Annulé.",
        "Casual": "Familier",
        "Casual, slangy": "Informel, argotique",
        "Check again": "Vérifier à nouveau",
        "Checking…": "Vérification…",
        "Choose a photo from the library": "Choisir une photo dans la galerie",
        "Claude connection": "Connexion à Claude",
        "Connected": "Connecté",
        "Connection error": "Erreur de connexion",
        "Context (optional)": "Contexte (facultatif)",
        "Copy": "Copier",
        "Copy English": "Copier l'anglais",
        "Copy translation": "Copier la traduction",
        "Couldn't connect": "Connexion impossible",
        "Couldn't create the export file.": "Impossible de créer le fichier d'export.",
        "Couldn't load": "Chargement impossible",
        "Couldn't load history.": "Impossible de charger l'historique.",
        "Couldn't load the list.": "Impossible de charger la liste.",
        "Couldn't parse the response. Try again.": "Impossible d'analyser la réponse. Réessayez.",
        "Couldn't process the image.": "Impossible de traiter l'image.",
        "Couldn't recognize speech. Type the text instead.": "Impossible de reconnaître la parole. Saisissez le texte à la place.",
        "Couldn't save to your study list.": "Impossible d'enregistrer dans votre liste d'étude.",
        "Dark": "Sombre",
        "Delete": "Supprimer",
        "Didn't catch that. Try again.": "Je n'ai pas compris. Réessayez.",
        "Done": "Terminé",
        "Double-tap to play": "Touchez deux fois pour écouter",
        "English": "Anglais",
        "English expression": "Expression anglaise",
        "Everyday conversational": "Conversation de tous les jours",
        "Explain": "Expliquer",
        "Explaining…": "Explication…",
        "Export": "Exporter",
        "Export list": "Exporter la liste",
        "Find phrasings": "Trouver des formulations",
        "Finding phrasings…": "Recherche de formulations…",
        "Formal and polite": "Formel et poli",
        "From library": "Depuis la galerie",
        "Get": "Comprendre",
        "Get it": "Comprendre",
        "History": "Historique",
        "How do you say it in English?": "Comment le dire en anglais ?",
        "How to say": "Comment dire",
        "In context": "En contexte",
        "Interface language": "Langue de l'interface",
        "Learned": "Appris",
        "Light": "Clair",
        "Listening": "À l'écoute",
        "Listening… tap to stop": "À l'écoute… touchez pour arrêter",
        "Loading…": "Chargement…",
        "Meaning": "Sens",
        "Microphone": "Microphone",
        "Microphone access": "Accès au microphone",
        "Mode": "Mode",
        "Model": "Modèle",
        "Native language": "Langue maternelle",
        "New expression": "Nouvelle expression",
        "New phrase": "Nouvelle phrase",
        "No Claude API key": "Pas de clé API Claude",
        "No Claude API key — options won't load. Add a key in Secrets.xcconfig.": "Pas de clé API Claude — les options ne se chargeront pas. Ajoutez une clé dans Secrets.xcconfig.",
        "No Claude API key — translation won't load. Add a key in Secrets.xcconfig.": "Pas de clé API Claude — la traduction ne se chargera pas. Ajoutez une clé dans Secrets.xcconfig.",
        "No Claude API key. Add one to continue.": "Pas de clé API Claude. Ajoutez-en une pour continuer.",
        "No Claude API key. Add one to get options.": "Pas de clé API Claude. Ajoutez-en une pour obtenir des options.",
        "No Claude API key. Add one to translate.": "Pas de clé API Claude. Ajoutez-en une pour traduire.",
        "No English text found in the photo. Try another image.": "Aucun texte anglais trouvé sur la photo. Essayez une autre image.",
        "No access to the microphone or speech recognition. Enable it in Settings, or type the text instead.": "Pas d'accès au microphone ou à la reconnaissance vocale. Activez-le dans Réglages, ou saisissez le texte.",
        "No connection": "Pas de connexion",
        "No connection. Check the internet and try again.": "Pas de connexion. Vérifiez Internet et réessayez.",
        "No history yet": "Pas encore d'historique",
        "Not learned": "Non appris",
        "Not now": "Plus tard",
        "Nothing yet": "Rien pour l'instant",
        "One moment…": "Un instant…",
        "Open result": "Ouvrir le résultat",
        "Photo translation": "Traduction photo",
        "Phrase tone": "Ton des phrases",
        "Play": "Écouter",
        "Play English": "Écouter l'anglais",
        "Play original": "Écouter l'original",
        "Play the English original": "Écouter l'original anglais",
        "Playing…": "Lecture…",
        "Polite": "Poli",
        "Reading and translating…": "Lecture et traduction…",
        "Ready": "Prêt",
        "Remove from study list": "Retirer de la liste d'étude",
        "Request": "Requête",
        "Request cancelled.": "Requête annulée.",
        "Retry": "Réessayer",
        "Russian": "Russe",
        "Save": "Enregistrer",
        "Save phrases from “Say”, “Understand”, or “Look” — or add them manually.": "Enregistrez des phrases depuis « Dire », « Comprendre » ou « Voir » — ou ajoutez-les manuellement.",
        "Save to study list": "Enregistrer dans la liste d'étude",
        "Say": "Dire",
        "Say it": "Dire",
        "See": "Voir",
        "See it": "Voir",
        "Service is overloaded — try later": "Service surchargé — réessayez plus tard",
        "Service is overloaded — try later.": "Service surchargé — réessayez plus tard.",
        "Service unavailable": "Service indisponible",
        "Service unavailable. Try later.": "Service indisponible. Réessayez plus tard.",
        "Settings": "Réglages",
        "Slang": "Argot",
        "Snap a sign, menu, or page — I'll read the English and translate it.": "Photographiez un panneau, un menu ou une page — je lirai l'anglais et le traduirai.",
        "Something went wrong": "Une erreur s'est produite",
        "Something went wrong. Try again.": "Une erreur s'est produite. Réessayez.",
        "Speech recognition is unavailable. Type the text instead.": "La reconnaissance vocale est indisponible. Saisissez le texte à la place.",
        "Speech voice": "Voix de synthèse",
        "Study": "Étudier",
        "Study list": "Liste d'étude",
        "System": "Système",
        "Take a photo": "Prendre une photo",
        "Tap and speak English": "Touchez et parlez en anglais",
        "Tap and speak Russian": "Touchez et parlez en russe",
        "Tap to speak English": "Touchez pour parler en anglais",
        "Tap to speak Russian": "Touchez pour parler en russe",
        "Tap to stop": "Touchez pour arrêter",
        "Text in any language": "Texte dans n'importe quelle langue",
        "Text recognition error.": "Erreur de reconnaissance de texte.",
        "The language of translations and explanations on the Get it screen.": "La langue des traductions et des explications sur l'écran Comprendre.",
        "The list is empty — nothing to export.": "La liste est vide — rien à exporter.",
        "The service didn't respond in time": "Le service n'a pas répondu à temps",
        "The service didn't respond in time. Try again.": "Le service n'a pas répondu à temps. Réessayez.",
        "Theme": "Thème",
        "To hear your English speech and translate it, the app needs the microphone. Nothing is recorded.": "Pour entendre votre anglais et le traduire, l'app a besoin du microphone. Rien n'est enregistré.",
        "To hear your question in Russian and find English phrases, the app needs the microphone. Nothing is recorded.": "Pour entendre votre question en russe et trouver des phrases en anglais, l'app a besoin du microphone. Rien n'est enregistré.",
        "To read English text on a sign or menu, the app needs the camera. Nothing is sent anywhere without your action.": "Pour lire le texte anglais d'un panneau ou d'un menu, l'app a besoin de la caméra. Rien n'est envoyé sans votre action.",
        "Tone & register": "Ton et registre",
        "Translate": "Traduire",
        "Translate text from a photo": "Traduire le texte d'une photo",
        "Translating…": "Traduction…",
        "Translation": "Traduction",
        "Type a phrase in Russian — I'll offer three options at different politeness levels.": "Saisissez une phrase en russe — je proposerai trois options à différents niveaux de politesse.",
        "Type or dictate an expression. In Translate I'll render its meaning; in Explain I'll tell you what it means, how formal or blunt it sounds, and what it compares to.": "Saisissez ou dictez une expression. En mode Traduire, j'en donne le sens ; en mode Expliquer, je vous dis ce qu'elle signifie, à quel point elle est formelle ou directe, et à quoi elle ressemble.",
        "Unexpected response from the service": "Réponse inattendue du service",
        "Version": "Version",
        "What do you want to say in Russian?": "Que voulez-vous dire en russe ?",
        "What does it mean?": "Qu'est-ce que ça veut dire ?",
        "Without a Claude API key, the card is saved without translation or examples.": "Sans clé API Claude, la carte est enregistrée sans traduction ni exemples.",
        "Your requests will appear here: how-to-say, translations, and photo translations.": "Vos demandes apparaîtront ici : comment dire, traductions et traductions photo.",
    ]

    public static let es: [String: String] = [
        "Studied language": "Idioma estudiado",
        "The language you're learning. Phrases are shown in it and all speech uses it.": "El idioma que estás aprendiendo. Las frases se muestran en él y toda la voz lo usa.",
        "French": "Francés",
        "Spanish": "Español",
        "Copy explanation": "Copiar la explicación",
        "Copy expression": "Copiar la expresión",
        "Clear": "Borrar",
        "Copied": "Copiado",
        "Explanation": "Explicación",
        "Text in the language you're learning": "Texto en el idioma que estudias",
        "Tap to speak the language you're learning": "Toca para hablar en el idioma que estudias",
        "Tap and speak the language you're learning": "Toca y habla en el idioma que estudias",
        "To hear your speech and translate it, the app needs the microphone. Nothing is recorded.": "Para escuchar tu voz y traducirla, la app necesita el micrófono. No se graba nada.",
        "What do you want to say?": "¿Qué quieres decir?",
        "Tap to speak your native language": "Toca para hablar en tu idioma nativo",
        "Tap and speak your native language": "Toca y habla en tu idioma nativo",
        "How do you say it?": "¿Cómo se dice?",
        "Ask by voice or type a phrase — I'll offer three options at different politeness levels.": "Pregunta por voz o escribe una frase: te ofreceré tres opciones con distintos niveles de cortesía.",
        "Type a phrase — I'll offer three options at different politeness levels.": "Escribe una frase: te ofreceré tres opciones con distintos niveles de cortesía.",
        "To hear you and find phrasings, the app needs the microphone. Nothing is recorded.": "Para escucharte y sugerir frases, la app necesita el micrófono. No se graba nada.",
        "About": "Acerca de",
        "Add": "Añadir",
        "Add expression": "Añadir expresión",
        "Adding translation and examples…": "Añadiendo traducción y ejemplos…",
        "Allow": "Permitir",
        "Analogy": "Analogía",
        "Another photo": "Otra foto",
        "Appearance": "Apariencia",
        "Ask by voice or type a phrase in Russian — I'll offer three options at different politeness levels.": "Pregunta por voz o escribe una frase en ruso: te ofreceré tres opciones con distintos niveles de cortesía.",
        "Camera access": "Acceso a la cámara",
        "Cancel": "Cancelar",
        "Cancelled.": "Cancelado.",
        "Casual": "Informal",
        "Casual, slangy": "Informal, con jerga",
        "Check again": "Comprobar de nuevo",
        "Checking…": "Comprobando…",
        "Choose a photo from the library": "Elegir una foto de la galería",
        "Claude connection": "Conexión con Claude",
        "Connected": "Conectado",
        "Connection error": "Error de conexión",
        "Context (optional)": "Contexto (opcional)",
        "Copy": "Copiar",
        "Copy English": "Copiar el inglés",
        "Copy translation": "Copiar la traducción",
        "Couldn't connect": "No se pudo conectar",
        "Couldn't create the export file.": "No se pudo crear el archivo de exportación.",
        "Couldn't load": "No se pudo cargar",
        "Couldn't load history.": "No se pudo cargar el historial.",
        "Couldn't load the list.": "No se pudo cargar la lista.",
        "Couldn't parse the response. Try again.": "No se pudo procesar la respuesta. Inténtalo de nuevo.",
        "Couldn't process the image.": "No se pudo procesar la imagen.",
        "Couldn't recognize speech. Type the text instead.": "No se pudo reconocer el habla. Escribe el texto.",
        "Couldn't save to your study list.": "No se pudo guardar en tu lista de estudio.",
        "Dark": "Oscuro",
        "Delete": "Eliminar",
        "Didn't catch that. Try again.": "No lo he captado. Inténtalo de nuevo.",
        "Done": "Hecho",
        "Double-tap to play": "Toca dos veces para reproducir",
        "English": "Inglés",
        "English expression": "Expresión en inglés",
        "Everyday conversational": "Conversación cotidiana",
        "Explain": "Explicar",
        "Explaining…": "Explicando…",
        "Export": "Exportar",
        "Export list": "Exportar la lista",
        "Find phrasings": "Buscar variantes",
        "Finding phrasings…": "Buscando variantes…",
        "Formal and polite": "Formal y cortés",
        "From library": "Desde la galería",
        "Get": "Entender",
        "Get it": "Entender",
        "History": "Historial",
        "How do you say it in English?": "¿Cómo se dice en inglés?",
        "How to say": "Cómo decir",
        "In context": "En contexto",
        "Interface language": "Idioma de la interfaz",
        "Learned": "Aprendido",
        "Light": "Claro",
        "Listening": "Escuchando",
        "Listening… tap to stop": "Escuchando… toca para parar",
        "Loading…": "Cargando…",
        "Meaning": "Significado",
        "Microphone": "Micrófono",
        "Microphone access": "Acceso al micrófono",
        "Mode": "Modo",
        "Model": "Modelo",
        "Native language": "Idioma nativo",
        "New expression": "Nueva expresión",
        "New phrase": "Nueva frase",
        "No Claude API key": "Sin clave de API de Claude",
        "No Claude API key — options won't load. Add a key in Secrets.xcconfig.": "Sin clave de API de Claude: las opciones no se cargarán. Añade una clave en Secrets.xcconfig.",
        "No Claude API key — translation won't load. Add a key in Secrets.xcconfig.": "Sin clave de API de Claude: la traducción no se cargará. Añade una clave en Secrets.xcconfig.",
        "No Claude API key. Add one to continue.": "Sin clave de API de Claude. Añade una para continuar.",
        "No Claude API key. Add one to get options.": "Sin clave de API de Claude. Añade una para obtener opciones.",
        "No Claude API key. Add one to translate.": "Sin clave de API de Claude. Añade una para traducir.",
        "No English text found in the photo. Try another image.": "No se encontró texto en inglés en la foto. Prueba con otra imagen.",
        "No access to the microphone or speech recognition. Enable it in Settings, or type the text instead.": "Sin acceso al micrófono o al reconocimiento de voz. Actívalo en Ajustes o escribe el texto.",
        "No connection": "Sin conexión",
        "No connection. Check the internet and try again.": "Sin conexión. Comprueba Internet e inténtalo de nuevo.",
        "No history yet": "Aún no hay historial",
        "Not learned": "No aprendido",
        "Not now": "Ahora no",
        "Nothing yet": "Nada todavía",
        "One moment…": "Un momento…",
        "Open result": "Abrir resultado",
        "Photo translation": "Traducción de foto",
        "Phrase tone": "Tono de las frases",
        "Play": "Reproducir",
        "Play English": "Reproducir el inglés",
        "Play original": "Reproducir el original",
        "Play the English original": "Reproducir el original en inglés",
        "Playing…": "Reproduciendo…",
        "Polite": "Cortés",
        "Reading and translating…": "Leyendo y traduciendo…",
        "Ready": "Listo",
        "Remove from study list": "Quitar de la lista de estudio",
        "Request": "Solicitud",
        "Request cancelled.": "Solicitud cancelada.",
        "Retry": "Reintentar",
        "Russian": "Ruso",
        "Save": "Guardar",
        "Save phrases from “Say”, “Understand”, or “Look” — or add them manually.": "Guarda frases desde «Decir», «Entender» o «Ver», o añádelas manualmente.",
        "Save to study list": "Guardar en la lista de estudio",
        "Say": "Decir",
        "Say it": "Decir",
        "See": "Ver",
        "See it": "Ver",
        "Service is overloaded — try later": "El servicio está saturado: inténtalo más tarde",
        "Service is overloaded — try later.": "El servicio está saturado: inténtalo más tarde.",
        "Service unavailable": "Servicio no disponible",
        "Service unavailable. Try later.": "Servicio no disponible. Inténtalo más tarde.",
        "Settings": "Ajustes",
        "Slang": "Jerga",
        "Snap a sign, menu, or page — I'll read the English and translate it.": "Haz una foto a un cartel, menú o página: leeré el inglés y lo traduciré.",
        "Something went wrong": "Algo salió mal",
        "Something went wrong. Try again.": "Algo salió mal. Inténtalo de nuevo.",
        "Speech recognition is unavailable. Type the text instead.": "El reconocimiento de voz no está disponible. Escribe el texto.",
        "Speech voice": "Voz de lectura",
        "Study": "Estudiar",
        "Study list": "Lista de estudio",
        "System": "Sistema",
        "Take a photo": "Hacer una foto",
        "Tap and speak English": "Toca y habla en inglés",
        "Tap and speak Russian": "Toca y habla en ruso",
        "Tap to speak English": "Toca para hablar en inglés",
        "Tap to speak Russian": "Toca para hablar en ruso",
        "Tap to stop": "Toca para parar",
        "Text in any language": "Texto en cualquier idioma",
        "Text recognition error.": "Error de reconocimiento de texto.",
        "The language of translations and explanations on the Get it screen.": "El idioma de las traducciones y explicaciones en la pantalla Entender.",
        "The list is empty — nothing to export.": "La lista está vacía: nada que exportar.",
        "The service didn't respond in time": "El servicio no respondió a tiempo",
        "The service didn't respond in time. Try again.": "El servicio no respondió a tiempo. Inténtalo de nuevo.",
        "Theme": "Tema",
        "To hear your English speech and translate it, the app needs the microphone. Nothing is recorded.": "Para escuchar tu inglés y traducirlo, la app necesita el micrófono. No se graba nada.",
        "To hear your question in Russian and find English phrases, the app needs the microphone. Nothing is recorded.": "Para escuchar tu pregunta en ruso y encontrar frases en inglés, la app necesita el micrófono. No se graba nada.",
        "To read English text on a sign or menu, the app needs the camera. Nothing is sent anywhere without your action.": "Para leer texto en inglés de un cartel o menú, la app necesita la cámara. No se envía nada sin tu acción.",
        "Tone & register": "Tono y registro",
        "Translate": "Traducir",
        "Translate text from a photo": "Traducir texto de una foto",
        "Translating…": "Traduciendo…",
        "Translation": "Traducción",
        "Type a phrase in Russian — I'll offer three options at different politeness levels.": "Escribe una frase en ruso: te ofreceré tres opciones con distintos niveles de cortesía.",
        "Type or dictate an expression. In Translate I'll render its meaning; in Explain I'll tell you what it means, how formal or blunt it sounds, and what it compares to.": "Escribe o dicta una expresión. En Traducir te doy su significado; en Explicar te digo qué significa, cómo de formal o directa suena y con qué se puede comparar.",
        "Unexpected response from the service": "Respuesta inesperada del servicio",
        "Version": "Versión",
        "What do you want to say in Russian?": "¿Qué quieres decir en ruso?",
        "What does it mean?": "¿Qué significa?",
        "Without a Claude API key, the card is saved without translation or examples.": "Sin una clave de API de Claude, la tarjeta se guarda sin traducción ni ejemplos.",
        "Your requests will appear here: how-to-say, translations, and photo translations.": "Tus solicitudes aparecerán aquí: cómo decir, traducciones y traducciones de fotos.",
    ]
}
